### ISSUE TITLE
The stack does not work on eu-west-3

### ISSUE THREAD

**Issue by vincedgy** [aws-quickstart/quickstart-tableau-server#59]
After multiple tries, with VPC creation and without, eu-west-3 can't work with this template.

**Comment by vsnyc** [comment]
@vincedgy - sorry for the late reply. This probably is because the [mapping][1] for `eu-west-3` doesn't yet existing in the template for cluster installations. I checked and see that it does exist for single server ubuntu and windows versions. Will add a test for it.

[1]: https://github.com/aws-quickstart/quickstart-tableau-server/blob/b400e6aafa55bc1a06097fc48ef8c49968cbd0c9/templates/tableau-cluster-linux.template#L298-L343

**Comment by vsnyc** [comment]
Closing older issues
