### ISSUE TITLE
Customer wants ability to use 2 AZs and have LB in private subnet 

### ISSUE THREAD

**Issue by dayyehm** [aws-quickstart/quickstart-tableau-server#70]
customer would like to be able to use 2 AZs instead of 3 and have the load balancer in a private subnet , customer wants the solution to allow such customization.

**Comment by vsnyc** [comment]
I discussed this with the customer. Using 2 AZs instead of 3 is not a best practice for a 3-node HA deployment of Tableau cluster. 

Keeping aside the recommendation, if it must be done, the workload template that deploys the Tableau server in a pre-existing VPC can be used. You can provide three private subnet IDs (two in one AZ and third in the second AZ) for the `PrivateSubnetIds` parameter and two public subnet IDs (one in each AZ) for the `PublicSubnetIds` parameter. 

I haven't tested it so additional configuration maybe required.
